#!/bin/bash
if command -v node &> /dev/null; then
    CWD=$(dirname "$0") # Current folder
    node "${CWD}/revstats.js" "$@"
else
    echo "Node.JS is missing"
    echo "apt install node.js"
    echo "brew install node.js"
    exit 1
fi
